name: 'Install Plugin Dependencies'
description: 'Install build dependencies for the Sidechain plugin on all platforms'

inputs:
  with-coverage:
    description: 'Install coverage tools (lcov)'
    required: false
    default: 'false'
  cache-version:
    description: 'Cache version - increment to invalidate cache'
    required: false
    default: '2'

runs:
  using: 'composite'
  steps:
    - name: Restore vcpkg and chocolatey cache (Windows)
      if: runner.os == 'Windows'
      id: packages-cache-windows
      uses: actions/cache/restore@v4
      with:
        path: |
          C:\vcpkg
          C:\ProgramData\chocolatey
          C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: sidechain-packages-v${{ inputs.cache-version }}-${{ hashFiles('.github/actions/install-deps/action.yml') }}
        restore-keys: |
          sidechain-packages-v${{ inputs.cache-version }}-

    - name: Restore Homebrew cache (macOS)
      if: runner.os == 'macOS'
      id: packages-cache-macos
      uses: actions/cache/restore@v4
      with:
        path: ~/Library/Caches/Homebrew
        key: sidechain-brew-v${{ inputs.cache-version }}-${{ hashFiles('.github/actions/install-deps/action.yml') }}
        restore-keys: |
          sidechain-brew-v${{ inputs.cache-version }}-

    - name: Restore apt cache (Linux)
      if: runner.os == 'Linux'
      id: packages-cache-linux
      uses: actions/cache/restore@v4
      with:
        path: /var/cache/apt/archives
        key: sidechain-apt-v${{ inputs.cache-version }}-${{ hashFiles('.github/actions/install-deps/action.yml') }}
        restore-keys: |
          sidechain-apt-v${{ inputs.cache-version }}-

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        PACKAGES=(
          libasound2-dev
          libjack-jackd2-dev
          ladspa-sdk
          libcurl4-openssl-dev
          libfreetype6-dev
          libx11-dev
          libxcomposite-dev
          libxcursor-dev
          libxext-dev
          libxinerama-dev
          libxrandr-dev
          libxrender-dev
          libwebkit2gtk-4.1-dev
          libglu1-mesa-dev
          mesa-common-dev
          ninja-build
          lld
          ccache
          libfftw3-dev
          libnotify-dev
        )
        if [ "${{ inputs.with-coverage }}" = "true" ]; then
          PACKAGES+=(lcov)
        fi
        sudo apt-get install -y "${PACKAGES[@]}"
        # Make apt cache readable/writable by current user for caching
        sudo chown -R $(id -u):$(id -g) /var/cache/apt/archives

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install ninja ccache openssl@3 fftw

    - name: Install Windows Dependencies
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install ninja ccache openssl -y -q
        # Install libcurl development package via vcpkg
        C:\vcpkg\vcpkg install curl:x64-windows
        # Set OpenSSL path for CMake
        echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL" >> $env:GITHUB_ENV
        # Set CURL_ROOT for CMake FindCURL module
        echo "CURL_ROOT=C:\vcpkg\installed\x64-windows" >> $env:GITHUB_ENV

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Save vcpkg and chocolatey cache (Windows)
      if: runner.os == 'Windows' && steps.packages-cache-windows.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          C:\vcpkg
          C:\ProgramData\chocolatey
          C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: sidechain-packages-v${{ inputs.cache-version }}-${{ hashFiles('.github/actions/install-deps/action.yml') }}

    - name: Save Homebrew cache (macOS)
      if: runner.os == 'macOS' && steps.packages-cache-macos.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ~/Library/Caches/Homebrew
        key: sidechain-brew-v${{ inputs.cache-version }}-${{ hashFiles('.github/actions/install-deps/action.yml') }}

    - name: Save apt cache (Linux)
      if: runner.os == 'Linux' && steps.packages-cache-linux.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: /var/cache/apt/archives
        key: sidechain-apt-v${{ inputs.cache-version }}-${{ hashFiles('.github/actions/install-deps/action.yml') }}
