import { useRef, useEffect, useState } from 'react'

interface WaveformDisplayProps {
  waveformUrl?: string
  progress: number // 0 to 1
  duration?: number // in seconds (unused but kept for API compatibility)
  isPlaying: boolean
  onClick?: (e: React.MouseEvent<HTMLDivElement>) => void
  className?: string
}

/**
 * WaveformDisplay - Shows a waveform image with playback position indicator
 * The waveform image is typically generated by the backend
 */
export function WaveformDisplay({
  waveformUrl,
  progress,
  isPlaying,
  onClick,
  className = '',
}: WaveformDisplayProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [_containerWidth, setContainerWidth] = useState(0)

  // Track container width for responsive positioning
  useEffect(() => {
    if (!containerRef.current) return

    const updateWidth = () => {
      setContainerWidth(containerRef.current?.offsetWidth || 0)
    }

    updateWidth()
    window.addEventListener('resize', updateWidth)
    return () => window.removeEventListener('resize', updateWidth)
  }, [])

  const positionPercent = progress * 100

  // If no waveform URL, show a simple progress bar with gradient
  if (!waveformUrl) {
    return (
      <div
        ref={containerRef}
        onClick={onClick}
        className={`relative h-12 bg-gradient-to-r from-coral-pink/10 via-rose-pink/10 to-lavender/10 rounded-lg overflow-hidden cursor-pointer group ${className}`}
      >
        {/* Background animated bars (when playing) */}
        {isPlaying && (
          <div className="absolute inset-0 flex items-center justify-around opacity-40">
            {Array.from({ length: 20 }).map((_, i) => (
              <div
                key={i}
                className="w-0.5 bg-coral-pink rounded-full animate-pulse"
                style={{
                  height: `${30 + Math.sin(i * 0.5) * 20}%`,
                  animationDelay: `${i * 0.05}s`,
                }}
              />
            ))}
          </div>
        )}

        {/* Static waveform fallback */}
        {!isPlaying && (
          <div className="absolute inset-0 flex items-center justify-around opacity-50">
            {Array.from({ length: 20 }).map((_, i) => (
              <div
                key={i}
                className="w-0.5 bg-foreground/30 rounded-full"
                style={{
                  height: `${30 + Math.sin(i * 0.5) * 20}%`,
                }}
              />
            ))}
          </div>
        )}

        {/* Playback position indicator */}
        <div
          className="absolute top-0 bottom-0 w-1 bg-gradient-to-b from-coral-pink to-rose-pink transition-none group-hover:w-2"
          style={{
            left: `${positionPercent}%`,
            transform: 'translateX(-50%)',
          }}
        />
      </div>
    )
  }

  // Show actual waveform image with position indicator
  return (
    <div
      ref={containerRef}
      onClick={onClick}
      className={`relative h-12 bg-card rounded-lg overflow-hidden cursor-pointer group ${className}`}
    >
      {/* Waveform image */}
      <img
        src={waveformUrl}
        alt="Waveform"
        className="w-full h-full object-cover"
        onError={(e) => {
          // Fallback to simple bars if image fails to load
          e.currentTarget.style.display = 'none'
        }}
      />

      {/* Dark overlay on unplayed portion */}
      <div
        className="absolute top-0 left-0 bottom-0 bg-black/30 transition-all"
        style={{
          width: `${(100 - positionPercent).toFixed(2)}%`,
        }}
      />

      {/* Playback position indicator */}
      <div
        className="absolute top-0 bottom-0 w-1 bg-gradient-to-b from-coral-pink to-rose-pink shadow-lg transition-none group-hover:w-2 group-hover:shadow-xl group-hover:from-coral-pink/90 group-hover:to-rose-pink/90"
        style={{
          left: `${positionPercent.toFixed(2)}%`,
          transform: 'translateX(-50%)',
          zIndex: 10,
        }}
      />

      {/* Hover indicator line */}
      <div className="absolute inset-0 opacity-0 group-hover:opacity-100 pointer-events-none">
        <div
          className="absolute top-0 bottom-0 w-0.5 bg-white/50"
          style={{
            left: 'var(--hover-x, 0)',
          }}
        />
      </div>
    </div>
  )
}
