name: 'Cache Build Directory'
description: 'Cache .cache and plugin/build directories for faster builds (JUCE, dependencies, and build artifacts)'

inputs:
  arch:
    description: 'CPU architecture (x86_64, arm64, universal)'
    required: false
    default: ''
  cache-version:
    description: 'Cache version - increment to invalidate cache'
    required: false
    default: '1'

runs:
  using: 'composite'
  steps:
    - name: Determine Architecture
      id: arch
      shell: bash
      run: |
        if [ -n "${{ inputs.arch }}" ]; then
          ARCH="${{ inputs.arch }}"
        elif [ "${{ runner.os }}" = "macOS" ]; then
          # Detect macOS architecture from matrix or system
          if [ -f /.dockerenv ]; then
            ARCH="x86_64"
          else
            ARCH=$(uname -m)
            if [ "$ARCH" = "arm64" ] && [[ "${{ runner.name }}" == *"ARM64"* ]]; then
              ARCH="arm64"
            elif [[ "${{ runner.name }}" == *"Intel"* ]]; then
              ARCH="x86_64"
            elif [[ "${{ runner.name }}" == *"universal"* ]]; then
              ARCH="universal"
            fi
          fi
        else
          ARCH="x86_64"
        fi
        echo "arch=$ARCH" >> $GITHUB_OUTPUT
        echo "Cache key: sidechain-build-${{ runner.os }}-$ARCH"

    - name: Cache Build Directory
      uses: actions/cache@v4
      with:
        path: |
          .cache
          plugin/build
        key: sidechain-build-v${{ inputs.cache-version }}-${{ runner.os }}-${{ steps.arch.outputs.arch }}-${{ hashFiles('plugin/CMakeLists.txt', 'plugin/cmake/**') }}
        restore-keys: |
          sidechain-build-v${{ inputs.cache-version }}-${{ runner.os }}-${{ steps.arch.outputs.arch }}-
          sidechain-build-v${{ inputs.cache-version }}-${{ runner.os }}-

    - name: Cache Homebrew Packages (macOS)
      if: runner.os == 'macOS'
      uses: actions/cache@v4
      with:
        path: ~/Library/Caches/Homebrew
        key: sidechain-brew-v${{ inputs.cache-version }}-${{ hashFiles('.github/actions/install-deps/action.yml') }}
        restore-keys: |
          sidechain-brew-v${{ inputs.cache-version }}-

    - name: Cache Chocolatey Packages (Windows)
      if: runner.os == 'Windows'
      uses: actions/cache@v4
      with:
        path: |
          C:\ProgramData\chocolatey
          C:\Program Files\OpenSSL
        key: sidechain-choco-v${{ inputs.cache-version }}-${{ hashFiles('.github/actions/install-deps/action.yml') }}
        restore-keys: |
          sidechain-choco-v${{ inputs.cache-version }}-
