name: 'Restore Build Cache'
description: 'Restore .cache, plugin/build, and ccache directories for faster builds'

inputs:
  arch:
    description: 'CPU architecture (x86_64, arm64, universal)'
    required: false
    default: ''
  cache-version:
    description: 'Cache version - increment to invalidate cache'
    required: false
    default: '2'

runs:
  using: 'composite'
  steps:
    - name: Determine Architecture
      id: arch
      shell: bash
      run: |
        if [ -n "${{ inputs.arch }}" ]; then
          ARCH="${{ inputs.arch }}"
        elif [ "${{ runner.os }}" = "macOS" ]; then
          # Detect macOS architecture from matrix or system
          if [ -f /.dockerenv ]; then
            ARCH="x86_64"
          else
            ARCH=$(uname -m)
            if [ "$ARCH" = "arm64" ] && [[ "${{ runner.name }}" == *"ARM64"* ]]; then
              ARCH="arm64"
            elif [[ "${{ runner.name }}" == *"Intel"* ]]; then
              ARCH="x86_64"
            elif [[ "${{ runner.name }}" == *"universal"* ]]; then
              ARCH="universal"
            fi
          fi
        else
          ARCH="x86_64"
        fi
        echo "arch=$ARCH" >> $GITHUB_OUTPUT
        echo "Cache key: sidechain-build-${{ runner.os }}-$ARCH"

    - name: Restore Build Cache
      id: build-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          .cache
          plugin/build
          ${{ runner.os == 'Linux' && '~/.cache/ccache' || runner.os == 'macOS' && '~/Library/Caches/ccache' || '' }}
        key: sidechain-build-v${{ inputs.cache-version }}-${{ runner.os }}-${{ steps.arch.outputs.arch }}-${{ hashFiles('plugin/CMakeLists.txt', 'plugin/cmake/**') }}
        restore-keys: |
          sidechain-build-v${{ inputs.cache-version }}-${{ runner.os }}-${{ steps.arch.outputs.arch }}-
          sidechain-build-v${{ inputs.cache-version }}-${{ runner.os }}-
