NetworkClient
ConnectionStatus
No connection (red indicator).
using NetworkClient::DeviceRegistrationCallback = std::function<void(Outcome<juce::String>)>
using NetworkClient::AuthenticationCallback = std::function<void(Outcome<std::pair<juce::String, juce::String>>)>
using NetworkClient::UploadCallback = std::function<void(Outcome<juce::String> audioUrl)>
using NetworkClient::FeedCallback = std::function<void(Outcome<juce::var> feedData)>
using NetworkClient::ProfilePictureCallback = std::function<void(Outcome<juce::String> pictureUrl)>
using NetworkClient::ConnectionStatusCallback = std::function<void(ConnectionStatus status)>
using NetworkClient::ResponseCallback = std::function<void(Outcome<juce::var> response)>
using NetworkClient::CommentCallback = std::function<void(Outcome<juce::var> comment)>
using NetworkClient::CommentsListCallback = std::function<void(Outcome<std::pair<juce::var, int>>)>
using NetworkClient::BinaryDataCallback = std::function<void(Outcome<juce::MemoryBlock> data)>
using NetworkClient::MultipartUploadCallback = std::function<void(Outcome<juce::var> response)>
using NetworkClient::NotificationCallback = std::function<void(Outcome<NotificationResult>)>
Config NetworkClient::config
juce::String NetworkClient::authToken
juce::String NetworkClient::currentUsername
juce::String NetworkClient::currentUserId
AuthenticationCallback NetworkClient::authCallback
ConnectionStatusCallback NetworkClient::connectionStatusCallback
std::atomic<ConnectionStatus> NetworkClient::connectionStatus
std::atomic<bool> NetworkClient::shuttingDown
std::atomic<int> NetworkClient::activeRequestCount
NetworkClient::NetworkClient(const Config &config=Config::development())
NetworkClient::~NetworkClient()
void NetworkClient::registerAccount(const juce::String &email, const juce::String &username, const juce::String &password, const juce::String &displayName, AuthenticationCallback callback)
Register a new user account.
email User's email address username Desired username password User's password displayName User's display name callback Called with authentication result (token, userId) or error
References Async::runVoid.
void NetworkClient::loginAccount(const juce::String &email, const juce::String &password, AuthenticationCallback callback)
Login with existing account credentials.
email User's email address password User's password callback Called with authentication result (token, userId) or error
References Async::runVoid.
void NetworkClient::setAuthenticationCallback(AuthenticationCallback callback)
Set the authentication callback for login/register operations.
callback Called when authentication completes
void NetworkClient::uploadAudio(const juce::String &recordingId, const juce::AudioBuffer< float > &audioBuffer, double sampleRate, UploadCallback callback=nullptr)
Upload audio to the server.
recordingId Unique identifier for this recording audioBuffer The audio data to upload sampleRate Sample rate of the audio callback Called with the CDN URL or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::runVoid.
void NetworkClient::uploadAudioWithMetadata(const juce::AudioBuffer< float > &audioBuffer, double sampleRate, const AudioUploadMetadata &metadata, UploadCallback callback=nullptr)
Upload audio with full metadata (title, BPM, key, genre).
audioBuffer The audio data to upload sampleRate Sample rate of the audio metadata Audio metadata (title, BPM, key, genre, etc.) callback Called with the CDN URL or error
References NetworkClient::AudioUploadMetadata::bpm, Outcome< T >::error, NetworkClient::AudioUploadMetadata::genre, isAuthenticated, NetworkClient::AudioUploadMetadata::key, Outcome< T >::ok, Async::runVoid, NetworkClient::AudioUploadMetadata::title.
void NetworkClient::getGlobalFeed(int limit=20, int offset=0, FeedCallback callback=nullptr)
Get the global feed (all posts).
limit Maximum number of posts to return offset Pagination offset callback Called with feed data or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::runVoid.
void NetworkClient::getTimelineFeed(int limit=20, int offset=0, FeedCallback callback=nullptr)
Get the timeline feed (posts from followed users).
limit Maximum number of posts to return offset Pagination offset callback Called with feed data or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::runVoid.
void NetworkClient::getTrendingFeed(int limit=20, int offset=0, FeedCallback callback=nullptr)
Get the trending feed (popular posts).
limit Maximum number of posts to return offset Pagination offset callback Called with feed data or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::runVoid.
void NetworkClient::likePost(const juce::String &activityId, const juce::String &emoji="", ResponseCallback callback=nullptr)
Like a post with optional emoji reaction.
activityId The post activity ID emoji Optional emoji reaction (empty for default like) callback Called with result or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::unlikePost(const juce::String &activityId, ResponseCallback callback=nullptr)
Unlike a post.
activityId The post activity ID callback Called with result or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::followUser(const juce::String &userId, ResponseCallback callback=nullptr)
Follow a user.
userId The user ID to follow callback Called with result or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::unfollowUser(const juce::String &userId, ResponseCallback callback=nullptr)
Unfollow a user.
userId The user ID to unfollow callback Called with result or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::uploadProfilePicture(const juce::File &imageFile, ProfilePictureCallback callback=nullptr)
Upload a profile picture.
imageFile The image file to upload callback Called with the CDN URL or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::runVoid.
void NetworkClient::changeUsername(const juce::String &newUsername, ResponseCallback callback=nullptr)
Change the current user's username.
newUsername The new username callback Called with result or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::getFollowers(const juce::String &userId, int limit=20, int offset=0, ResponseCallback callback=nullptr)
Get a user's followers list.
userId The user ID limit Maximum number of results offset Pagination offset callback Called with followers data or error
References Async::runVoid.
void NetworkClient::getFollowing(const juce::String &userId, int limit=20, int offset=0, ResponseCallback callback=nullptr)
Get a user's following list.
userId The user ID limit Maximum number of results offset Pagination offset callback Called with following data or error
References Async::runVoid.
void NetworkClient::getComments(const juce::String &postId, int limit=20, int offset=0, CommentsListCallback callback=nullptr)
Get comments for a post.
postId The post ID limit Maximum number of comments to return offset Pagination offset callback Called with comments list and total count or error
References Async::runVoid.
void NetworkClient::createComment(const juce::String &postId, const juce::String &content, const juce::String &parentId="", CommentCallback callback=nullptr)
Create a new comment on a post.
postId The post ID content The comment text parentId Optional parent comment ID for replies callback Called with the created comment or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::getCommentReplies(const juce::String &commentId, int limit=20, int offset=0, CommentsListCallback callback=nullptr)
Get replies to a comment.
commentId The parent comment ID limit Maximum number of replies to return offset Pagination offset callback Called with replies list and total count or error
References Async::runVoid.
void NetworkClient::updateComment(const juce::String &commentId, const juce::String &content, CommentCallback callback=nullptr)
Update an existing comment.
commentId The comment ID to update content The new comment text callback Called with the updated comment or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::deleteComment(const juce::String &commentId, ResponseCallback callback=nullptr)
Delete a comment.
commentId The comment ID to delete callback Called with result or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::likeComment(const juce::String &commentId, ResponseCallback callback=nullptr)
Like a comment.
commentId The comment ID callback Called with result or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::unlikeComment(const juce::String &commentId, ResponseCallback callback=nullptr)
Unlike a comment.
commentId The comment ID callback Called with result or error
References Outcome< T >::error, isAuthenticated, Async::runVoid.
void NetworkClient::get(const juce::String &endpoint, ResponseCallback callback)
void NetworkClient::post(const juce::String &endpoint, const juce::var &data, ResponseCallback callback)
void NetworkClient::put(const juce::String &endpoint, const juce::var &data, ResponseCallback callback)
void NetworkClient::del(const juce::String &endpoint, ResponseCallback callback)
void NetworkClient::getAbsolute(const juce::String &absoluteUrl, ResponseCallback callback, const juce::StringPairArray &customHeaders=juce::StringPairArray())
void NetworkClient::postAbsolute(const juce::String &absoluteUrl, const juce::var &data, ResponseCallback callback, const juce::StringPairArray &customHeaders=juce::StringPairArray())
void NetworkClient::getBinaryAbsolute(const juce::String &absoluteUrl, BinaryDataCallback callback, const juce::StringPairArray &customHeaders=juce::StringPairArray())
void NetworkClient::uploadMultipartAbsolute(const juce::String &absoluteUrl, const juce::String &fieldName, const juce::MemoryBlock &fileData, const juce::String &fileName, const juce::String &mimeType, const std::map< juce::String, juce::String > &extraFields, MultipartUploadCallback callback, const juce::StringPairArray &customHeaders=juce::StringPairArray())
void NetworkClient::trackPlay(const juce::String &activityId, ResponseCallback callback=nullptr)
void NetworkClient::trackListenDuration(const juce::String &activityId, double durationSeconds, ResponseCallback callback=nullptr)
void NetworkClient::getNotifications(int limit=20, int offset=0, NotificationCallback callback=nullptr)
void NetworkClient::getNotificationCounts(std::function< void(int unseen, int unread)> callback)
void NetworkClient::markNotificationsRead(ResponseCallback callback=nullptr)
void NetworkClient::markNotificationsSeen(ResponseCallback callback=nullptr)
void NetworkClient::searchUsers(const juce::String &query, int limit=20, int offset=0, ResponseCallback callback=nullptr)
void NetworkClient::getTrendingUsers(int limit=20, ResponseCallback callback=nullptr)
void NetworkClient::getFeaturedProducers(int limit=20, ResponseCallback callback=nullptr)
void NetworkClient::getSuggestedUsers(int limit=20, ResponseCallback callback=nullptr)
void NetworkClient::getUsersByGenre(const juce::String &genre, int limit=20, int offset=0, ResponseCallback callback=nullptr)
void NetworkClient::getAvailableGenres(ResponseCallback callback=nullptr)
void NetworkClient::getSimilarUsers(const juce::String &userId, int limit=10, ResponseCallback callback=nullptr)
void NetworkClient::searchPosts(const juce::String &query, const juce::String &genre="", int bpmMin=0, int bpmMax=200, const juce::String &key="", int limit=20, int offset=0, ResponseCallback callback=nullptr)
void NetworkClient::getSearchSuggestions(const juce::String &query, int limit=5, ResponseCallback callback=nullptr)
void NetworkClient::getStoriesFeed(ResponseCallback callback=nullptr)
void NetworkClient::viewStory(const juce::String &storyId, ResponseCallback callback=nullptr)
void NetworkClient::getStoryViews(const juce::String &storyId, ResponseCallback callback=nullptr)
void NetworkClient::uploadStory(const juce::AudioBuffer< float > &audioBuffer, double sampleRate, const juce::var &midiData, int bpm=0, const juce::String &key="", const juce::StringArray &genres=juce::StringArray(), ResponseCallback callback=nullptr)
void NetworkClient::setAuthToken(const juce::String &token)
Set the authentication token.
token The JWT authentication token
bool NetworkClient::isAuthenticated() const
Check if currently authenticated.
true if authenticated, false otherwise
Referenced by changeUsername, createComment, deleteComment, followUser, getGlobalFeed, getTimelineFeed, getTrendingFeed, likeComment, likePost, unfollowUser, unlikeComment, unlikePost, updateComment, uploadAudio, uploadAudioWithMetadata, uploadProfilePicture.
const juce::String & NetworkClient::getBaseUrl() const
Get the base URL for API requests.
The configured base URL
const juce::String & NetworkClient::getCurrentUsername() const
Get the current authenticated username.
The username, or empty string if not authenticated
const juce::String & NetworkClient::getCurrentUserId() const
Get the current authenticated user ID.
The user ID, or empty string if not authenticated
ConnectionStatus NetworkClient::getConnectionStatus() const
void NetworkClient::setConnectionStatusCallback(ConnectionStatusCallback callback)
void NetworkClient::checkConnection()
void NetworkClient::cancelAllRequests()
bool NetworkClient::isShuttingDown() const
void NetworkClient::setConfig(const Config &newConfig)
const Config & NetworkClient::getConfig() const
NetworkClient::RequestResult NetworkClient::makeAbsoluteRequestSync(const juce::String &absoluteUrl, const juce::String &method="GET", const juce::var &data=juce::var(), bool requireAuth=false, const juce::StringPairArray &customHeaders=juce::StringPairArray(), juce::MemoryBlock *binaryData=nullptr)
NetworkClient::RequestResult NetworkClient::makeRequestWithRetry(const juce::String &endpoint, const juce::String &method="GET", const juce::var &data=juce::var(), bool requireAuth=false)
NetworkClient::RequestResult NetworkClient::makeAbsoluteRequestWithRetry(const juce::String &absoluteUrl, const juce::String &method="GET", const juce::var &data=juce::var(), bool requireAuth=false, const juce::StringPairArray &customHeaders=juce::StringPairArray(), juce::MemoryBlock *binaryData=nullptr)
juce::var NetworkClient::makeRequest(const juce::String &endpoint, const juce::String &method="GET", const juce::var &data=juce::var(), bool requireAuth=false)
NetworkClient::RequestResult NetworkClient::uploadMultipartData(const juce::String &endpoint, const juce::String &fieldName, const juce::MemoryBlock &fileData, const juce::String &fileName, const juce::String &mimeType, const std::map< juce::String, juce::String > &extraFields={})
NetworkClient::RequestResult NetworkClient::uploadMultipartDataAbsolute(const juce::String &absoluteUrl, const juce::String &fieldName, const juce::MemoryBlock &fileData, const juce::String &fileName, const juce::String &mimeType, const std::map< juce::String, juce::String > &extraFields={}, const juce::StringPairArray &customHeaders=juce::StringPairArray())
juce::String NetworkClient::getAuthHeader() const
void NetworkClient::handleAuthResponse(const juce::var &response)
void NetworkClient::updateConnectionStatus(ConnectionStatus status)
bool NetworkClient::requireAuth(Callback &&callback) const
juce::MemoryBlock NetworkClient::encodeAudioToMP3(const juce::AudioBuffer< float > &buffer, double sampleRate)
juce::MemoryBlock NetworkClient::encodeAudioToWAV(const juce::AudioBuffer< float > &buffer, double sampleRate)
juce::String NetworkClient::buildApiPath(const char *path)
int NetworkClient::parseStatusCode(const juce::StringPairArray &headers)