HttpAudioPlayer
std::function<void(const juce::String& postId)> HttpAudioPlayer::onPlaybackStarted
Called when playback starts.
Referenced by play.
std::function<void(const juce::String& postId)> HttpAudioPlayer::onPlaybackPaused
Called when playback pauses.
Referenced by pause.
std::function<void(const juce::String& postId)> HttpAudioPlayer::onPlaybackStopped
Called when playback stops (end of file).
Referenced by stop.
std::function<void(const juce::String& postId)> HttpAudioPlayer::onLoadingStarted
Called when loading starts.
Referenced by loadAndPlay.
std::function<void(const juce::String& postId, bool success)> HttpAudioPlayer::onLoadingComplete
Called when loading completes.
std::function<void(const juce::String& postId, double progress)> HttpAudioPlayer::onProgressUpdate
Called periodically with playback progress.
std::function<void(const juce::String& postId)> HttpAudioPlayer::onPlaybackFinished
Called when playback finishes (reached end of audio) - for auto-play.
Referenced by processBlock.
std::function<void(const juce::String& postId)> HttpAudioPlayer::onAutoPlayNext
Called when auto-play moves to next post.
Referenced by processBlock.
juce::AudioFormatManager HttpAudioPlayer::formatManager
std::unique_ptr<juce::AudioFormatReaderSource> HttpAudioPlayer::readerSource
std::unique_ptr<juce::ResamplingAudioSource> HttpAudioPlayer::resamplingSource
std::atomic<bool> HttpAudioPlayer::playing
std::atomic<bool> HttpAudioPlayer::loading
std::atomic<bool> HttpAudioPlayer::muted
std::atomic<float> HttpAudioPlayer::volume
std::atomic<bool> HttpAudioPlayer::autoPlayEnabled
juce::StringArray HttpAudioPlayer::playlistPostIds
juce::StringArray HttpAudioPlayer::playlistAudioUrls
juce::CriticalSection HttpAudioPlayer::playlistLock
std::atomic<bool> HttpAudioPlayer::audioFocusEnabled
std::atomic<bool> HttpAudioPlayer::pausedByDAW
std::atomic<bool> HttpAudioPlayer::wasPlayingBeforeDAW
juce::String HttpAudioPlayer::currentPostId
juce::String HttpAudioPlayer::currentAudioUrl
double HttpAudioPlayer::currentSampleRate
int HttpAudioPlayer::currentBlockSize
juce::Time HttpAudioPlayer::playbackStartTime
bool HttpAudioPlayer::playbackStarted
juce::CriticalSection HttpAudioPlayer::audioLock
std::map<juce::String, CachedAudio> HttpAudioPlayer::audioCache
size_t HttpAudioPlayer::maxCacheSize
size_t HttpAudioPlayer::currentCacheSize
juce::CriticalSection HttpAudioPlayer::cacheLock
NetworkClient* HttpAudioPlayer::networkClient
std::unique_ptr<ProgressTimer> HttpAudioPlayer::progressTimer
HttpAudioPlayer::HttpAudioPlayer()
HttpAudioPlayer::~HttpAudioPlayer() override
void HttpAudioPlayer::loadAndPlay(const juce::String &postId, const juce::String &audioUrl)
Load and play audio from a URL.
postId Unique identifier for the post audioUrl URL to the audio file (MP3, WAV, etc.)
References onLoadingStarted, pause, play, stop.
Referenced by playNext, playPrevious, processBlock.
void HttpAudioPlayer::play()
Play the currently loaded audio.
References onPlaybackStarted.
Referenced by loadAndPlay, onDAWTransportStopped, togglePlayPause.
void HttpAudioPlayer::pause()
Pause playback.
References onPlaybackPaused.
Referenced by loadAndPlay, onDAWTransportStarted, togglePlayPause.
void HttpAudioPlayer::stop()
Stop playback and reset position.
References onPlaybackStopped.
Referenced by loadAndPlay, processBlock.
void HttpAudioPlayer::togglePlayPause()
Toggle between play and pause.
References pause, play.
void HttpAudioPlayer::seekToPosition(double positionSeconds)
Seek to a position.
positionSeconds Position in seconds
Referenced by playPrevious, seekToNormalizedPosition.
void HttpAudioPlayer::seekToNormalizedPosition(double normalizedPosition)
Seek to a normalized position (0.0 to 1.0).
normalizedPosition Position from 0 to 1
References getDurationSeconds, seekToPosition.
bool HttpAudioPlayer::isPlaying() const
bool HttpAudioPlayer::isLoading() const
double HttpAudioPlayer::getPositionSeconds() const
Get current playback position in seconds.
Referenced by getPlaybackProgress, playPrevious.
double HttpAudioPlayer::getDurationSeconds() const
Get total duration in seconds.
Referenced by getPlaybackProgress, seekToNormalizedPosition.
double HttpAudioPlayer::getPlaybackProgress() const
Get playback progress (0.0 to 1.0).
References getDurationSeconds, getPositionSeconds.
juce::String HttpAudioPlayer::getCurrentPostId() const
Get the currently playing post ID.
bool HttpAudioPlayer::isPostPlaying(const juce::String &postId) const
Check if a specific post is currently playing.
void HttpAudioPlayer::setVolume(float newVolume)
Set volume (0.0 to 1.0).
float HttpAudioPlayer::getVolume() const
Get current volume.
void HttpAudioPlayer::setMuted(bool shouldMute)
Mute/unmute.
bool HttpAudioPlayer::isMuted() const
void HttpAudioPlayer::setAutoPlayEnabled(bool enabled)
Enable/disable auto-play next post when current finishes.
bool HttpAudioPlayer::isAutoPlayEnabled() const
void HttpAudioPlayer::setPlaylist(const juce::StringArray &postIds, const juce::StringArray &audioUrls)
Set the playlist of posts for auto-play and pre-buffering.
References getCurrentPlaylistIndex, preloadAudio.
int HttpAudioPlayer::getCurrentPlaylistIndex() const
Get index of current post in playlist (-1 if not in playlist).
Referenced by playNext, playPrevious, processBlock, setPlaylist.
void HttpAudioPlayer::playNext()
Skip to next post in playlist.
References getCurrentPlaylistIndex, loadAndPlay.
void HttpAudioPlayer::playPrevious()
Skip to previous post in playlist.
References getCurrentPlaylistIndex, getPositionSeconds, loadAndPlay, seekToPosition.
void HttpAudioPlayer::onDAWTransportStarted()
Notify that DAW transport is playing If audio focus is enabled, this will pause feed playback.
References pause.
void HttpAudioPlayer::onDAWTransportStopped()
Notify that DAW transport has stopped If audio focus is enabled and we were playing before, resume playback.
References play.
void HttpAudioPlayer::setAudioFocusEnabled(bool enabled)
Enable/disable audio focus (pause when DAW plays).
bool HttpAudioPlayer::isAudioFocusEnabled() const
void HttpAudioPlayer::processBlock(juce::AudioBuffer< float > &buffer, int numSamples)
Process and mix playback audio into the output buffer Should be called from the audio thread only.
buffer The audio buffer to mix into numSamples Number of samples to process
References getCurrentPlaylistIndex, loadAndPlay, onAutoPlayNext, onPlaybackFinished, stop.
void HttpAudioPlayer::prepareToPlay(double sampleRate, int blockSize)
Prepare for playback Should be called from PluginProcessor::prepareToPlay.
sampleRate The DAW's sample rate blockSize Maximum block size
void HttpAudioPlayer::releaseResources()
Release resources Should be called from PluginProcessor::releaseResources.
void HttpAudioPlayer::clearCache()
Clear the audio cache.
void HttpAudioPlayer::setMaxCacheSize(size_t bytes)
Set maximum cache size in bytes (default: 50MB).
size_t HttpAudioPlayer::getCurrentCacheSize() const
Get current cache size in bytes.
void HttpAudioPlayer::preloadAudio(const juce::String &postId, const juce::String &audioUrl)
Preload audio for a post (for seamless playback).
References Async::runVoid.
Referenced by setPlaylist.
void HttpAudioPlayer::setNetworkClient(NetworkClient *client)
Set NetworkClient for HTTP requests.
void HttpAudioPlayer::changeListenerCallback(juce::ChangeBroadcaster *source) override
void HttpAudioPlayer::evictCacheIfNeeded(size_t bytesNeeded)
void HttpAudioPlayer::addToCache(const juce::String &postId, std::unique_ptr< juce::MemoryBlock > data)
juce::MemoryBlock * HttpAudioPlayer::getFromCache(const juce::String &postId)
void HttpAudioPlayer::downloadAudio(const juce::String &postId, const juce::String &url)
void HttpAudioPlayer::loadFromMemory(const juce::String &postId, juce::MemoryBlock &audioData)