StreamChatClient
ConnectionStatus
Not connected to getstream.io.
using StreamChatClient::TokenCallback = std::function<void(Outcome<TokenResult>)>
using StreamChatClient::ChannelsCallback = std::function<void(Outcome<std::vector<Channel>>)>
using StreamChatClient::MessagesCallback = std::function<void(Outcome<std::vector<Message>>)>
using StreamChatClient::MessageCallback = std::function<void(Outcome<Message>)>
using StreamChatClient::PresenceCallback = std::function<void(Outcome<std::vector<UserPresence>>)>
using StreamChatClient::ConnectionStatusCallback = std::function<void(ConnectionStatus status)>
using StreamChatClient::MessageReceivedCallback = std::function<void(const Message& message, const juce::String& channelId)>
using StreamChatClient::TypingCallback = std::function<void(const juce::String& userId, bool isTyping)>
using StreamChatClient::PresenceChangedCallback = std::function<void(const UserPresence& presence)>
using StreamChatClient::AudioSnippetCallback = std::function<void(Outcome<AudioSnippetResult>)>
NetworkClient* StreamChatClient::networkClient
Config StreamChatClient::config
juce::String StreamChatClient::chatToken
juce::String StreamChatClient::apiKey
juce::String StreamChatClient::currentUserId
juce::String StreamChatClient::backendAuthToken
std::unique_ptr<juce::StreamingSocket> StreamChatClient::webSocket
std::atomic<bool> StreamChatClient::wsConnected
juce::String StreamChatClient::wsUrl
std::atomic<ConnectionStatus> StreamChatClient::connectionStatus
ConnectionStatusCallback StreamChatClient::connectionStatusCallback
MessageReceivedCallback StreamChatClient::messageReceivedCallback
TypingCallback StreamChatClient::typingCallback
PresenceChangedCallback StreamChatClient::presenceChangedCallback
std::function<void(int)> StreamChatClient::unreadCountCallback
juce::String StreamChatClient::watchedChannelType
juce::String StreamChatClient::watchedChannelId
juce::String StreamChatClient::lastSeenMessageId
std::unique_ptr<juce::Timer> StreamChatClient::channelPollTimer
std::unique_ptr<juce::Timer> StreamChatClient::unreadPollTimer
StreamChatClient::StreamChatClient(NetworkClient *networkClient, const Config &config=Config::development())
StreamChatClient::~StreamChatClient()
void StreamChatClient::setNetworkClient(NetworkClient *client)
Set the network client for HTTP requests.
client Pointer to the NetworkClient instance
void StreamChatClient::fetchToken(const juce::String &backendAuthToken, TokenCallback callback)
Fetch a getstream.io chat token from the backend.
backendAuthToken The backend authentication token callback Called with token result or error
References Outcome< T >::error, Outcome< T >::getError, Outcome< T >::isError.
void StreamChatClient::setToken(const juce::String &token, const juce::String &apiKey, const juce::String &userId)
Set the chat token and API credentials directly.
token The getstream.io chat token apiKey The getstream.io API key userId The current user ID
bool StreamChatClient::isAuthenticated() const
Check if authenticated with getstream.io.
true if token and API key are set
Referenced by addMembers, addReaction, createDirectChannel, createGroupChannel, deleteChannel, deleteMessage, getChannel, markChannelRead, queryChannels, queryMessages, removeMembers, removeReaction, sendMessage, updateChannel, updateMessage, uploadAudioSnippet.
void StreamChatClient::createDirectChannel(const juce::String &targetUserId, std::function< void(Outcome< Channel >)> callback)
Create a direct messaging channel with another user.
targetUserId The user ID to message callback Called with the created channel or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::createGroupChannel(const juce::String &channelId, const juce::String &name, const std::vector< juce::String > &memberIds, std::function< void(Outcome< Channel >)> callback)
Create a group channel.
channelId Unique channel identifier name Channel display name memberIds List of user IDs to add as members callback Called with the created channel or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::queryChannels(ChannelsCallback callback, int limit=20, int offset=0)
Query channels for the current user.
callback Called with list of channels or error limit Maximum number of channels to return offset Pagination offset
References isAuthenticated, Async::run.
void StreamChatClient::getChannel(const juce::String &channelType, const juce::String &channelId, std::function< void(Outcome< Channel >)> callback)
Get a specific channel by type and ID.
channelType Channel type (e.g., "messaging", "team") channelId Channel identifier callback Called with the channel or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::deleteChannel(const juce::String &channelType, const juce::String &channelId, std::function< void(Outcome< void >)> callback)
Delete a channel.
channelType Channel type channelId Channel identifier callback Called with result or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::leaveChannel(const juce::String &channelType, const juce::String &channelId, std::function< void(Outcome< void >)> callback)
Leave a channel.
channelType Channel type channelId Channel identifier callback Called with result or error
References removeMembers.
void StreamChatClient::addMembers(const juce::String &channelType, const juce::String &channelId, const std::vector< juce::String > &memberIds, std::function< void(Outcome< void >)> callback)
Add members to a channel.
channelType Channel type channelId Channel identifier memberIds List of user IDs to add callback Called with result or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::removeMembers(const juce::String &channelType, const juce::String &channelId, const std::vector< juce::String > &memberIds, std::function< void(Outcome< void >)> callback)
Remove members from a channel.
channelType Channel type channelId Channel identifier memberIds List of user IDs to remove callback Called with result or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
Referenced by leaveChannel.
void StreamChatClient::updateChannel(const juce::String &channelType, const juce::String &channelId, const juce::String &name, const juce::var &extraData, std::function< void(Outcome< Channel >)> callback)
Update channel metadata.
channelType Channel type channelId Channel identifier name New channel name extraData Additional channel data callback Called with updated channel or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::sendMessage(const juce::String &channelType, const juce::String &channelId, const juce::String &text, const juce::var &extraData, MessageCallback callback)
Send a text message to a channel.
channelType Channel type channelId Channel identifier text Message text content extraData Additional message data (e.g., reply_to, attachments) callback Called with the sent message or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
Referenced by sendMessageWithAudio.
void StreamChatClient::queryMessages(const juce::String &channelType, const juce::String &channelId, int limit, int offset, MessagesCallback callback)
Query messages from a channel.
channelType Channel type channelId Channel identifier limit Maximum number of messages to return offset Pagination offset callback Called with list of messages or error
References isAuthenticated, Async::run.
void StreamChatClient::updateMessage(const juce::String &channelType, const juce::String &channelId, const juce::String &messageId, const juce::String &newText, MessageCallback callback)
Update an existing message.
channelType Channel type channelId Channel identifier messageId Message identifier newText Updated message text callback Called with updated message or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::deleteMessage(const juce::String &channelType, const juce::String &channelId, const juce::String &messageId, std::function< void(Outcome< void >)> callback)
Delete a message.
channelType Channel type channelId Channel identifier messageId Message identifier callback Called with result or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::addReaction(const juce::String &channelType, const juce::String &channelId, const juce::String &messageId, const juce::String &reactionType, std::function< void(Outcome< void >)> callback)
Add a reaction to a message.
channelType Channel type channelId Channel identifier messageId Message identifier reactionType Reaction emoji or type callback Called with result or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::removeReaction(const juce::String &channelType, const juce::String &channelId, const juce::String &messageId, const juce::String &reactionType, std::function< void(Outcome< void >)> callback)
Remove a reaction from a message.
channelType Channel type channelId Channel identifier messageId Message identifier reactionType Reaction emoji or type to remove callback Called with result or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::markChannelRead(const juce::String &channelType, const juce::String &channelId, std::function< void(Outcome< void >)> callback)
Mark a channel as read.
channelType Channel type channelId Channel identifier callback Called with result or error
References Outcome< T >::error, isAuthenticated, Outcome< T >::ok, Async::run.
void StreamChatClient::uploadAudioSnippet(const juce::AudioBuffer< float > &audioBuffer, double sampleRate, AudioSnippetCallback callback)
Upload an audio snippet for sharing in messages.
audioBuffer The audio data to upload sampleRate Sample rate of the audio callback Called with upload result (URL, duration) or error
References Outcome< T >::error, Outcome< T >::getError, isAuthenticated, Outcome< T >::isError, Async::runVoid.
Referenced by sendMessageWithAudio.
void StreamChatClient::sendMessageWithAudio(const juce::String &channelType, const juce::String &channelId, const juce::String &text, const juce::AudioBuffer< float > &audioBuffer, double sampleRate, MessageCallback callback)
Send a message with an audio attachment.
channelType Channel type channelId Channel identifier text Optional message text audioBuffer The audio data to attach sampleRate Sample rate of the audio callback Called with the sent message or error
References Outcome< T >::error, Outcome< T >::getError, Outcome< T >::getValue, Outcome< T >::isError, sendMessage, uploadAudioSnippet.
void StreamChatClient::searchMessages(const juce::String &query, const juce::var &channelFilters, int limit, int offset, MessagesCallback callback)
void StreamChatClient::queryPresence(const std::vector< juce::String > &userIds, PresenceCallback callback)
void StreamChatClient::updateStatus(const juce::String &status, const juce::var &extraData, std::function< void(Outcome< void >)> callback)
void StreamChatClient::watchChannel(const juce::String &channelType, const juce::String &channelId)
void StreamChatClient::unwatchChannel()
bool StreamChatClient::isWatchingChannel() const
void StreamChatClient::setMessageReceivedCallback(MessageReceivedCallback callback)
void StreamChatClient::setTypingCallback(TypingCallback callback)
void StreamChatClient::setPresenceChangedCallback(PresenceChangedCallback callback)
void StreamChatClient::setUnreadCountCallback(std::function< void(int totalUnread)> callback)
void StreamChatClient::sendTypingIndicator(const juce::String &channelType, const juce::String &channelId, bool isTyping)
void StreamChatClient::connectWebSocket()
void StreamChatClient::disconnectWebSocket()
bool StreamChatClient::isWebSocketConnected() const
void StreamChatClient::setConnectionStatusCallback(ConnectionStatusCallback callback)
ConnectionStatus StreamChatClient::getConnectionStatus() const
void StreamChatClient::pollWatchedChannel()
void StreamChatClient::pollUnreadCount()
juce::String StreamChatClient::getStreamBaseUrl() const
juce::String StreamChatClient::buildAuthHeaders() const
juce::var StreamChatClient::makeStreamRequest(const juce::String &endpoint, const juce::String &method, const juce::var &data=juce::var())
void StreamChatClient::updateConnectionStatus(ConnectionStatus status)
void StreamChatClient::handleWebSocketMessage(const juce::String &message)
void StreamChatClient::parseWebSocketEvent(const juce::var &event)
juce::String StreamChatClient::generateDirectChannelId(const juce::String &userId1, const juce::String &userId2)
StreamChatClient::Channel StreamChatClient::parseChannel(const juce::var &channelData)
StreamChatClient::Message StreamChatClient::parseMessage(const juce::var &messageData)
StreamChatClient::UserPresence StreamChatClient::parsePresence(const juce::var &userData)