BufferAudioPlayer
std::function<void()> BufferAudioPlayer::onPlaybackStarted
Called when playback starts.
Referenced by play.
std::function<void()> BufferAudioPlayer::onPlaybackPaused
Called when playback pauses.
Referenced by pause.
std::function<void()> BufferAudioPlayer::onPlaybackStopped
Called when playback stops (end of file).
Referenced by stop.
std::function<void(double progress)> BufferAudioPlayer::onProgressUpdate
Called periodically with playback progress.
std::function<void()> BufferAudioPlayer::onPlaybackFinished
Called when playback finishes (reached end of audio).
Referenced by processBlock.
juce::AudioBuffer<float> BufferAudioPlayer::audioBuffer
double BufferAudioPlayer::bufferSampleRate
int BufferAudioPlayer::numChannels
int BufferAudioPlayer::totalSamples
std::atomic<bool> BufferAudioPlayer::playing
std::atomic<bool> BufferAudioPlayer::muted
std::atomic<float> BufferAudioPlayer::volume
std::atomic<juce::int64> BufferAudioPlayer::currentSamplePosition
double BufferAudioPlayer::outputSampleRate
double BufferAudioPlayer::resamplingRatio
juce::LagrangeInterpolator BufferAudioPlayer::interpolator
juce::CriticalSection BufferAudioPlayer::bufferLock
std::unique_ptr<ProgressTimer> BufferAudioPlayer::progressTimer
BufferAudioPlayer::BufferAudioPlayer()
BufferAudioPlayer::~BufferAudioPlayer()
void BufferAudioPlayer::loadBuffer(const juce::AudioBuffer< float > &buffer, double sampleRate)
Load audio buffer for playback.
buffer The audio buffer to play (copied internally) sampleRate The sample rate of the buffer
References getDurationSeconds.
void BufferAudioPlayer::clear()
Clear the loaded buffer.
References stop.
void BufferAudioPlayer::play()
Play the loaded audio.
References onPlaybackStarted.
Referenced by togglePlayPause.
void BufferAudioPlayer::pause()
Pause playback.
References onPlaybackPaused.
Referenced by togglePlayPause.
void BufferAudioPlayer::stop()
Stop playback and reset position.
References onPlaybackStopped.
Referenced by clear, processBlock.
void BufferAudioPlayer::togglePlayPause()
Toggle between play and pause.
References pause, play.
void BufferAudioPlayer::seekToPosition(double positionSeconds)
Seek to a position.
positionSeconds Position in seconds
Referenced by seekToNormalizedPosition.
void BufferAudioPlayer::seekToNormalizedPosition(double normalizedPosition)
Seek to a normalized position (0.0 to 1.0).
normalizedPosition Position from 0 to 1
References getDurationSeconds, seekToPosition.
bool BufferAudioPlayer::isPlaying() const
bool BufferAudioPlayer::hasBuffer() const
double BufferAudioPlayer::getPositionSeconds() const
Get current playback position in seconds.
Referenced by getPlaybackProgress.
double BufferAudioPlayer::getDurationSeconds() const
Get total duration in seconds.
Referenced by getPlaybackProgress, loadBuffer, seekToNormalizedPosition.
double BufferAudioPlayer::getPlaybackProgress() const
Get playback progress (0.0 to 1.0).
References getDurationSeconds, getPositionSeconds.
void BufferAudioPlayer::setVolume(float newVolume)
Set volume (0.0 to 1.0).
float BufferAudioPlayer::getVolume() const
Get current volume.
void BufferAudioPlayer::setMuted(bool shouldMute)
Mute/unmute.
bool BufferAudioPlayer::isMuted() const
void BufferAudioPlayer::processBlock(juce::AudioBuffer< float > &buffer, int numSamples)
Process and mix playback audio into the output buffer Should be called from the audio thread only.
buffer The audio buffer to mix into numSamples Number of samples to process
References onPlaybackFinished, stop.
void BufferAudioPlayer::prepareToPlay(double sampleRate, int blockSize)
Prepare for playback Should be called from PluginProcessor::prepareToPlay.
sampleRate The DAW's sample rate blockSize Maximum block size
void BufferAudioPlayer::releaseResources()
Release resources Should be called from PluginProcessor::releaseResources.
double BufferAudioPlayer::samplePositionToSeconds(juce::int64 samplePos) const
juce::int64 BufferAudioPlayer::secondsToSamplePosition(double seconds) const