Outcome
std::optional<T> Outcome< T >::value
juce::String Outcome< T >::errorMessage
bool Outcome< T >::hasValue
static Outcome< T > Outcome< T >::ok(const T &value)
Create a successful result with a value.
Referenced by StreamChatClient::addMembers, StreamChatClient::addReaction, StreamChatClient::createDirectChannel, StreamChatClient::createGroupChannel, StreamChatClient::deleteChannel, StreamChatClient::deleteMessage, StreamChatClient::getChannel, NetworkClient::getGlobalFeed, NetworkClient::getTimelineFeed, NetworkClient::getTrendingFeed, Outcome< int >::map, StreamChatClient::markChannelRead, Outcome< int >::recover, StreamChatClient::removeMembers, StreamChatClient::removeReaction, StreamChatClient::sendMessage, StreamChatClient::updateChannel, StreamChatClient::updateMessage, NetworkClient::uploadAudio, NetworkClient::uploadAudioWithMetadata, NetworkClient::uploadProfilePicture.
static Outcome< T > Outcome< T >::ok(T &&value)
Create a successful result with a moved value.
static Outcome< T > Outcome< T >::error(const juce::String &message)
Create a failed result with an error message.
Referenced by StreamChatClient::addMembers, StreamChatClient::addReaction, NetworkClient::changeUsername, NetworkClient::createComment, StreamChatClient::createDirectChannel, StreamChatClient::createGroupChannel, StreamChatClient::deleteChannel, NetworkClient::deleteComment, StreamChatClient::deleteMessage, StreamChatClient::fetchToken, Outcome< int >::flatMap, NetworkClient::followUser, StreamChatClient::getChannel, NetworkClient::getGlobalFeed, NetworkClient::getTimelineFeed, NetworkClient::getTrendingFeed, NetworkClient::likeComment, NetworkClient::likePost, Outcome< int >::map, Outcome< int >::mapError, StreamChatClient::markChannelRead, StreamChatClient::removeMembers, StreamChatClient::removeReaction, StreamChatClient::sendMessage, StreamChatClient::sendMessageWithAudio, Outcome< void >::then, NetworkClient::unfollowUser, NetworkClient::unlikeComment, NetworkClient::unlikePost, StreamChatClient::updateChannel, NetworkClient::updateComment, StreamChatClient::updateMessage, NetworkClient::uploadAudio, StreamChatClient::uploadAudioSnippet, NetworkClient::uploadAudioWithMetadata, NetworkClient::uploadProfilePicture.
bool Outcome< T >::isOk() const noexcept
Returns true if this result contains a value.
bool Outcome< T >::isError() const noexcept
Returns true if this result contains an error.
Referenced by StreamChatClient::fetchToken, StreamChatClient::sendMessageWithAudio, StreamChatClient::uploadAudioSnippet.
Outcome< T >::operator bool() const noexcept
Implicit bool conversion - true if ok.
const T & Outcome< T >::getValue() const
Get the value.
Only call if isOk() returns true. Logs an error and returns default T if called on an error result.
Referenced by StreamChatClient::sendMessageWithAudio.
T & Outcome< T >::getValue()
Get the value (mutable).
Only call if isOk() returns true.
T Outcome< T >::getValueOr(const T &defaultValue) const
Get the value or a default if this is an error result.
T Outcome< T >::getValueOrElse(std::function< T()> defaultFn) const
Get the value or compute a default if this is an error result.
const juce::String & Outcome< T >::getError() const noexcept
Get the error message.
Returns empty string if this is an ok result.
Referenced by StreamChatClient::fetchToken, StreamChatClient::sendMessageWithAudio, StreamChatClient::uploadAudioSnippet.
Outcome< U > Outcome< T >::map(std::function< U(const T &)> fn) const
Transform the value if ok, propagate error if not.
Example: Outcome<int> count = fetchItems().map([](auto& items) { return items.size(); });
Outcome< U > Outcome< T >::flatMap(std::function< Outcome< U >(const T &)> fn) const
Transform the value with a function that returns an Outcome.
Useful for chaining operations that can fail. Example: Outcome<Profile> profile = fetchUser(id).flatMap([](auto& u) { return fetchProfile(u.profileId); });
const Outcome< T > & Outcome< T >::onSuccess(std::function< void(const T &)> fn) const
Execute a function if this is ok, return self for chaining.
const Outcome< T > & Outcome< T >::onError(std::function< void(const juce::String &)> fn) const
Execute a function if this is an error, return self for chaining.
const Outcome< T > & Outcome< T >::logIfError(const juce::String &context="") const
Log the error if this is an error result.
Outcome< T > Outcome< T >::mapError(std::function< juce::String(const juce::String &)> fn) const
Transform the error message if this is an error result.
Outcome< T > Outcome< T >::recover(std::function< T(const juce::String &)> fn) const
Provide a recovery value if this is an error.
Outcome< T >::Outcome(const T &val)
Outcome< T >::Outcome(T &&val)
Outcome< T >::Outcome(const juce::String &error, bool)