Async
void Async::runVoid(std::function< void()> work, std::function< void()> onComplete=nullptr)
Run void work on background thread with completion callback.
work Function to execute on background thread onComplete Called on message thread when work completes (may be nullptr)
Referenced by NetworkClient::changeUsername, NetworkClient::createComment, NetworkClient::deleteComment, NetworkClient::followUser, NetworkClient::getCommentReplies, NetworkClient::getComments, NetworkClient::getFollowers, NetworkClient::getFollowing, NetworkClient::getGlobalFeed, NetworkClient::getTimelineFeed, NetworkClient::getTrendingFeed, NetworkClient::likeComment, NetworkClient::likePost, NetworkClient::loginAccount, HttpAudioPlayer::preloadAudio, NetworkClient::registerAccount, NetworkClient::unfollowUser, NetworkClient::unlikeComment, NetworkClient::unlikePost, NetworkClient::updateComment, NetworkClient::uploadAudio, StreamChatClient::uploadAudioSnippet, NetworkClient::uploadAudioWithMetadata, NetworkClient::uploadProfilePicture.
int Async::delay(int delayMs, std::function< void()> callback)
Execute a callback after a delay on the message thread.
Returns an ID that can be used to cancel the delay. delayMs Delay in milliseconds callback Function to call after delay Timer ID for cancellation (0 if failed)
void Async::cancelDelay(int timerId)
Cancel a pending delayed callback.
timerId Timer ID returned from delay()
void Async::debounce(const juce::String &key, int delayMs, std::function< void()> callback)
Debounce calls to a function - only executes after a period of inactivity.
Useful for search inputs, resize handlers, etc. Each call resets the timer. The callback only fires when no new calls have been made for delayMs milliseconds. key Unique identifier for this debounce group delayMs Delay in milliseconds to wait after last call callback Function to execute after debounce period
void Async::cancelDebounce(const juce::String &key)
Cancel any pending debounced callback for the given key.
key The debounce group to cancel
void Async::cancelAllDebounces()
Cancel all pending debounced callbacks.
void Async::throttle(const juce::String &key, int periodMs, std::function< void()> callback)
Throttle calls to a function - executes at most once per period.
Unlike debounce, this ensures the callback fires periodically during rapid calls, rather than waiting for calls to stop. key Unique identifier for this throttle group periodMs Minimum time between executions in milliseconds callback Function to execute
void Async::cancelThrottle(const juce::String &key)
Cancel throttling for the given key.
key The throttle group to cancel
void Async::run(std::function< T()> work, std::function< void(T)> onComplete)
Run work on a background thread and deliver result to message thread.
T The return type of the work function work Function to execute on background thread onComplete Callback receiving result, called on message thread
Referenced by StreamChatClient::addMembers, StreamChatClient::addReaction, StreamChatClient::createDirectChannel, StreamChatClient::createGroupChannel, StreamChatClient::deleteChannel, StreamChatClient::deleteMessage, StreamChatClient::getChannel, StreamChatClient::markChannelRead, StreamChatClient::queryChannels, StreamChatClient::queryMessages, StreamChatClient::removeMembers, StreamChatClient::removeReaction, StreamChatClient::sendMessage, StreamChatClient::updateChannel, StreamChatClient::updateMessage.