TextEditorStyler
void TextEditorStyler::style(juce::TextEditor &editor, const juce::String &placeholder="")
Apply standard single-line text editor styling.
Sets colors, font, placeholder, and common properties.
References setPlaceholder.
Referenced by styleEmail, styleNumeric, stylePassword, styleUrl, styleUsername.
void TextEditorStyler::stylePassword(juce::TextEditor &editor, const juce::String &placeholder="Password")
Apply password field styling (masked input).
References style.
void TextEditorStyler::styleMultiline(juce::TextEditor &editor, const juce::String &placeholder="")
Apply multiline text editor styling.
Enables word wrap, scrollbars, and newline on return.
References setPlaceholder.
void TextEditorStyler::styleEmail(juce::TextEditor &editor, const juce::String &placeholder="Email")
Apply email field styling with appropriate keyboard hints.
References style.
void TextEditorStyler::styleUsername(juce::TextEditor &editor, const juce::String &placeholder="Username")
Apply username field styling (lowercase, restricted characters).
References style.
void TextEditorStyler::styleNumeric(juce::TextEditor &editor, const juce::String &placeholder="")
Apply numeric-only field styling.
References style.
void TextEditorStyler::styleUrl(juce::TextEditor &editor, const juce::String &placeholder="https://")
Apply URL field styling.
References style.
void TextEditorStyler::setInputRestrictions(juce::TextEditor &editor, int maxLength, const juce::String &allowedChars="")
Set input character restrictions.
maxLength Maximum number of characters (0 = unlimited) allowedChars String of allowed characters (empty = all allowed)
void TextEditorStyler::setPlaceholder(juce::TextEditor &editor, const juce::String &placeholder)
Set placeholder text with appropriate styling.
Referenced by style, styleMultiline.
void TextEditorStyler::styleReadOnly(juce::TextEditor &editor)
Apply read-only styling (non-editable display).
void TextEditorStyler::setErrorState(juce::TextEditor &editor, bool hasError)
Apply error state styling (red border).
References clearErrorState.
void TextEditorStyler::clearErrorState(juce::TextEditor &editor)
Reset to normal state (remove error styling).
Referenced by setErrorState.