ImageLoader
using ImageLoader::ImageCallback = std::function<void(const juce::Image&)>
void ImageLoader::load(const juce::String &url, ImageCallback callback, int width=0, int height=0)
Load an image from URL asynchronously.
If cached, callback fires immediately on the message thread. If not cached, downloads in background and calls back on message thread. url The image URL to load callback Called with the image (or null image on failure) width Optional: resize to this width (0 = original size) height Optional: resize to this height (0 = original size)
Referenced by preload, PostCard::setPost.
juce::Image ImageLoader::loadSync(const juce::String &url)
Load an image synchronously (blocks until loaded or failed).
Use sparingly - prefer async load() for UI code. url The image URL to load The loaded image, or null image on failure
bool ImageLoader::isCached(const juce::String &url)
Check if an image is already cached.
Referenced by preload.
juce::Image ImageLoader::getCached(const juce::String &url)
Get a cached image if available (doesn't trigger download).
Returns null image if not cached.
void ImageLoader::preload(const juce::StringArray &urls)
Pre-load images into cache (useful for known upcoming images).
References isCached, load.
void ImageLoader::setMaxSize(size_t maxImages)
Set maximum number of images to cache (default: 100).
When exceeded, least recently used images are evicted.
size_t ImageLoader::getSize()
Get current cache size.
void ImageLoader::clear()
Clear all cached images.
void ImageLoader::evict(const juce::String &url)
Remove a specific URL from cache.
Stats ImageLoader::getStats()
void ImageLoader::resetStats()
juce::String ImageLoader::getInitials(const juce::String &name)
Get initials from a name (e.g., "John Doe" -> "JD", "alice" -> "A").
void ImageLoader::drawCircularAvatar(juce::Graphics &g, juce::Rectangle< int > bounds, const juce::Image &image, const juce::String &initials, juce::Colour bgColor, juce::Colour textColor, float fontSize=14.0f)
Draw a circular avatar with image or initials fallback.
g Graphics context bounds Rectangle to draw in image The avatar image (can be null) initials Initials to show if image is null bgColor Background color for initials placeholder textColor Text color for initials fontSize Font size for initials (default 14.0f)
void ImageLoader::setNetworkClient(NetworkClient *client)
Set NetworkClient for HTTP requests (optional - falls back to JUCE URL if not set).