UI
void UI::drawCard(juce::Graphics &g, juce::Rectangle< float > bounds, juce::Colour fillColor, juce::Colour borderColor=juce::Colours::transparentBlack, float cornerRadius=8.0f, float borderWidth=1.0f)
Draw a rounded rectangle card with fill and optional border.
g Graphics context bounds Rectangle to draw fillColor Background fill color borderColor Border color (use transparent for no border) cornerRadius Corner radius (default 8.0f) borderWidth Border thickness (default 1.0f)
Referenced by drawCard, drawCardWithHover.
void UI::drawCard(juce::Graphics &g, juce::Rectangle< int > bounds, juce::Colour fillColor, juce::Colour borderColor=juce::Colours::transparentBlack, float cornerRadius=8.0f, float borderWidth=1.0f)
Overload for int bounds.
References drawCard.
void UI::drawCardWithHover(juce::Graphics &g, juce::Rectangle< int > bounds, juce::Colour normalColor, juce::Colour hoverColor, juce::Colour borderColor, bool isHovered, float cornerRadius=8.0f)
Draw a card with hover state support.
References drawCard.
void UI::drawBadge(juce::Graphics &g, juce::Rectangle< int > bounds, const juce::String &text, juce::Colour bgColor, juce::Colour textColor, float fontSize=11.0f, float cornerRadius=4.0f)
Draw a small badge/tag with text (e.g., "120 BPM", "NEW").
g Graphics context bounds Rectangle to draw text Badge text bgColor Background color textColor Text color fontSize Font size (default 11.0f) cornerRadius Corner radius (default 4.0f)
juce::Rectangle< int > UI::drawPillBadge(juce::Graphics &g, int x, int y, const juce::String &text, juce::Colour bgColor, juce::Colour textColor, float fontSize=11.0f, int hPadding=8, int vPadding=4)
Draw a pill-shaped badge that auto-sizes to text.
Returns the actual bounds used.
void UI::drawButton(juce::Graphics &g, juce::Rectangle< int > bounds, const juce::String &text, juce::Colour bgColor, juce::Colour textColor, bool isHovered=false, float cornerRadius=6.0f)
Draw a rounded button with text.
g Graphics context bounds Button bounds text Button text bgColor Background color textColor Text color isHovered Whether button is being hovered cornerRadius Corner radius (default 6.0f)
void UI::drawOutlineButton(juce::Graphics &g, juce::Rectangle< int > bounds, const juce::String &text, juce::Colour borderColor, juce::Colour textColor, bool isHovered=false, float cornerRadius=6.0f)
Draw an outline-style button.
void UI::drawIconButton(juce::Graphics &g, juce::Rectangle< int > bounds, juce::Colour bgColor, bool isHovered=false)
Draw a circular icon button background.
void UI::drawIcon(juce::Graphics &g, juce::Rectangle< int > bounds, const juce::String &icon, juce::Colour color, float fontSize=16.0f)
Draw a simple icon character (emoji or symbol).
void UI::drawProgressBar(juce::Graphics &g, juce::Rectangle< int > bounds, float progress, juce::Colour bgColor, juce::Colour fillColor, float cornerRadius=4.0f)
Draw a horizontal progress bar.
void UI::drawLoadingSpinner(juce::Graphics &g, juce::Rectangle< int > bounds, juce::Colour color, float rotation)
Draw a loading spinner indicator.
void UI::drawDivider(juce::Graphics &g, int x, int y, int width, juce::Colour color, float thickness=1.0f)
Draw a horizontal divider line.
void UI::drawVerticalDivider(juce::Graphics &g, int x, int y, int height, juce::Colour color, float thickness=1.0f)
Draw a vertical divider line.
juce::String UI::truncateWithEllipsis(const juce::String &text, const juce::Font &font, int maxWidth)
Truncate text to fit within maxWidth, adding ellipsis if needed.
text The text to truncate font Font to measure with maxWidth Maximum width in pixels Truncated text with "..." if needed
Referenced by drawTruncatedText.
void UI::drawTruncatedText(juce::Graphics &g, const juce::String &text, juce::Rectangle< int > bounds, juce::Colour color, juce::Justification justification=juce::Justification::centredLeft)
Draw text with automatic ellipsis truncation.
References truncateWithEllipsis.
int UI::getTextWidth(const juce::Graphics &g, const juce::String &text)
Calculate text width for the current font.
int UI::getTextWidth(const juce::Font &font, const juce::String &text)
void UI::drawDropShadow(juce::Graphics &g, juce::Rectangle< int > bounds, juce::Colour shadowColor, int radius=4, juce::Point< int > offset={0, 2})
Draw a drop shadow beneath a rectangle.
Call before drawing the actual element.
void UI::drawTooltip(juce::Graphics &g, juce::Rectangle< int > bounds, const juce::String &text, juce::Colour bgColor, juce::Colour textColor)
Draw a tooltip box with text.