# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from pathlib import Path

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here.
sys.path.insert(0, os.path.abspath('.'))

# Get the project root directory (two levels up from docs/)
project_root = Path(__file__).parent.parent

# -- Project information -----------------------------------------------------

project = 'Sidechain'
copyright = '2025, Joopal'
author = 'Joopal'

# Get version from git or use default
try:
    import subprocess
    version = subprocess.check_output(
        ['git', 'describe', '--tags', '--always'],
        cwd=project_root,
        stderr=subprocess.DEVNULL
    ).decode().strip()
    release = version
except:
    version = '0.0.0'
    release = '0.0.0'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'myst_parser',  # Markdown support
]

# Only enable Breathe/Exhale if Doxygen XML exists
_doxygen_xml_check = Path(__file__).parent / "doxygen" / "xml"
if not _doxygen_xml_check.exists():
    _doxygen_xml_check = Path(__file__).parent.parent / "plugin" / "build-docs" / "docs" / "doxygen" / "xml"

if _doxygen_xml_check.exists():
    extensions.extend(['breathe', 'exhale'])
    _has_doxygen = True
else:
    _has_doxygen = False
    print("WARNING: Doxygen XML not found - API documentation will not be generated")

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'doxygen']

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme.
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2980B9',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []  # Add '_static' directory if you have custom static files

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    '**': [
        'versions.html',
        'relations.html',
        'sourcelink.html',
        'searchbox.html',
    ]
}

# -- Breathe configuration ---------------------------------------------------

if _has_doxygen:
    # Breathe is the bridge between Doxygen and Sphinx
    # The Doxygen XML path will be set by CMake via environment variable
    # For manual builds, it should be in docs/doxygen/xml relative to this file
    doxygen_xml_path = os.environ.get('DOXYGEN_XML_DIR')
    if not doxygen_xml_path:
        # Default to source directory for manual builds
        doxygen_xml_path = str(Path(__file__).parent / "doxygen" / "xml")
        # If that doesn't exist, try build directory (common when using CMake)
        if not os.path.exists(doxygen_xml_path):
            # Try to find it relative to common build locations
            build_xml = Path(__file__).parent.parent / "plugin" / "build-docs" / "docs" / "doxygen" / "xml"
            if build_xml.exists():
                doxygen_xml_path = str(build_xml)

    breathe_projects = {
        "Sidechain": doxygen_xml_path
    }

    breathe_default_project = "Sidechain"

    # Tell Breathe where to find the Doxygen XML output
    # Show all members, including documented ones with their comments
    breathe_default_members = ('members', 'undoc-members')
    breathe_show_define_initializer = True
    breathe_show_enumvalues_initializer = True
    # Ensure detailed descriptions are shown
    breathe_default_domain = 'cpp'

# -- Exhale configuration ----------------------------------------------------

if _has_doxygen:
    # Setup the exhale extension
    # Exhale needs to know where the Doxygen XML is
    exhale_args = {
        # Required arguments
        "containmentFolder":     "./api",
        "rootFileName":          "library_root.rst",
        "rootFileTitle":          "API Reference",
        "doxygenStripFromPath":  "..",
        # Suggested optional arguments
        "createTreeView":        True,
        "exhaleExecutesDoxygen": False,  # We'll run Doxygen separately via CMake
        "exhaleDoxygenStdin":    "",  # Not needed since we run Doxygen separately
        # Optional arguments
        "verboseBuild":          False,
        "generateBreatheFileDirectives": True,
        # Show full documentation including comments
        "fullToctreeMaxDepth":   4,
        # Exhale uses breathe_projects to find the Doxygen XML
        # We'll ensure this is built before Sphinx runs
    }

# -- Intersphinx configuration -----------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    # JUCE documentation doesn't provide intersphinx, so we'll skip it
    # 'juce': ('https://juce.com/learn/documentation', None),
}

# -- MyST Parser configuration ------------------------------------------------

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",  # Auto-convert URLs to clickable links
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

# -- Additional configuration ------------------------------------------------

# Suppress warnings for missing Doxygen XML files during initial setup
suppress_warnings = []

# Enable numbered figures
numfig = True
